version: '3.8'

services:
  express-app:
    image: yumeangelica/express_app:latest
    container_name: express-app
    ports:
      - "3000:8080" # Map host port 3000 to container port 8080
    restart: unless-stopped

  watchtower:
    image: containrrr/watchtower
    container_name: watchtower
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      - WATCHTOWER_POLL_INTERVAL=30  # Check for updates every 30 seconds
    restart: unless-stopped